const FETCH_GET_TODOS_REQUESTS = 'FETCH_GET_TODOS_REQUESTS';
const FETCH_GET_TODOS_SUCCESS = 'FETCH_GET_TODOS_SUCCESS';
const FETCH_GET_TODOS_FAILURE = 'FETCH_GET_TODOS_FAILURE';

const FETCH_ADD_TODO_REQUESTS = 'FETCH_GET_TODOS_REQUESTS';
const FETCH_ADD_TODO_SUCCESS = 'FETCH_GET_TODOS_SUCCESS';
const FETCH_ADD_TODO_FAILURE = 'FETCH_GET_TODOS_FAILURE';

const FETCH_UPDATE_TODO_REQUESTS = 'FETCH_UPDATE_TODOS_REQUESTS';
const FETCH_UPDATE_TODO_SUCCESS = 'FETCH_UPDATE_TODOS_SUCCESS';
const FETCH_UPDATE_TODO_FAILURE = 'FETCH_UPDATE_TODOS_FAILURE';

export {
  FETCH_GET_TODOS_REQUESTS,
  FETCH_GET_TODOS_SUCCESS,
  FETCH_GET_TODOS_FAILURE,
  FETCH_ADD_TODO_REQUESTS,
  FETCH_ADD_TODO_SUCCESS,
  FETCH_ADD_TODO_FAILURE,
  FETCH_UPDATE_TODO_REQUESTS,
  FETCH_UPDATE_TODO_SUCCESS,
  FETCH_UPDATE_TODO_FAILURE
};
